### ISSUE TITLE
Add documentation on CMIP preprocessor

### ISSUE THREAD

**Issue by BSchilperoort** [WAM2layers/WAM2layers#421]
https://github.com/WAM2layers/WAM2layers/pull/394 added support for CMIP. However some documentation is still missing:

- [ ] an example CMIP config
- [ ] an CMIP example dataset
- [ ] explanation on which variables from which mip tables are required

Copied from the PR:
<hr>

**Current input data requirements**

Note that this data loader is made for the specific files from MPI which are on a 3hr and 6hr frequency: this has not been generalized yet.

If you use variables from the following tables, the preprocessor should work for other climate models as well:
- mip table "3hr" vars: `hfls`, `pr`
- mip table "6hrPlevPt" vars: `hus`, `huss`, `ua`, `uas`, `va`, `vas`
- mip table "6hrLev" var: `ps`

<details>
<summary>example config</summary>

```yaml
# General
preprocessed_data_folder: ./preprocessed_data
output_folder: ./output_data_fw
tracking_direction: forward
calendar: standard

# Preprocessing
filename_template: ./input_data/{variable}_*.nc
preprocess_start_date: "2030-03-01T00:00"
preprocess_end_date: "2030-08-01T00:00"
parallel_preprocess: True
level_type: pressure_levels
levels: [5000, 25000, 50000, 60000, 70000, 85000, 92500]

# Tracking
tracking_domain: null  # use full domain of preprocessed data
# tracking_domain: [0, 50, 10, 55]  # use subdomain of preprocessed data; west south east north
tracking_start_date: "2030-03-14T00:00"
tracking_end_date: "2030-08-01T00:00"

# Tagging
tagging_region: [-10, 35, 40, 60]  # alternative to mask file; west south east north
tagging_start_date: "2030-03-14T00:00"
tagging_end_date: "2030-05-14T00:00"

input_frequency: "6h"
timestep: 600  # timestep in seconds
output_frequency: "1D"
restart: False
periodic_boundary: true
kvf: 3
```

</details>
